// Flag quiz data. Deliberately a static list rather than an API call: the
// flag itself is an embed image, which Discord's CDN fetches on the viewer's
// behalf, so a round needs no outbound request from the bot at all. That
// makes ,geography work even on a host with outbound HTTPS blocked — unlike
// the gif and image commands.
//
// Codes are ISO 3166-1 alpha-2, which is both what flagcdn.com keys on and
// what the flag emoji is derived from.
const COUNTRIES = [
  ['ad', 'Andorra'],
  ['ae', 'United Arab Emirates', ['uae']],
  ['af', 'Afghanistan'],
  ['ag', 'Antigua and Barbuda'],
  ['al', 'Albania'],
  ['am', 'Armenia'],
  ['ao', 'Angola'],
  ['ar', 'Argentina'],
  ['at', 'Austria'],
  ['au', 'Australia'],
  ['az', 'Azerbaijan'],
  ['ba', 'Bosnia and Herzegovina', ['bosnia']],
  ['bb', 'Barbados'],
  ['bd', 'Bangladesh'],
  ['be', 'Belgium'],
  ['bf', 'Burkina Faso'],
  ['bg', 'Bulgaria'],
  ['bh', 'Bahrain'],
  ['bi', 'Burundi'],
  ['bj', 'Benin'],
  ['bn', 'Brunei'],
  ['bo', 'Bolivia'],
  ['br', 'Brazil'],
  ['bs', 'Bahamas'],
  ['bt', 'Bhutan'],
  ['bw', 'Botswana'],
  ['by', 'Belarus'],
  ['bz', 'Belize'],
  ['ca', 'Canada'],
  ['cd', 'Democratic Republic of the Congo', ['dr congo', 'drc', 'congo kinshasa']],
  ['cf', 'Central African Republic', ['car']],
  ['cg', 'Republic of the Congo', ['congo', 'congo brazzaville']],
  ['ch', 'Switzerland'],
  ['ci', 'Ivory Coast', ['cote divoire', 'côte d’ivoire']],
  ['cl', 'Chile'],
  ['cm', 'Cameroon'],
  ['cn', 'China', ['peoples republic of china', 'prc']],
  ['co', 'Colombia'],
  ['cr', 'Costa Rica'],
  ['cu', 'Cuba'],
  ['cv', 'Cape Verde', ['cabo verde']],
  ['cy', 'Cyprus'],
  ['cz', 'Czechia', ['czech republic']],
  ['de', 'Germany', ['deutschland']],
  ['dj', 'Djibouti'],
  ['dk', 'Denmark'],
  ['dm', 'Dominica'],
  ['do', 'Dominican Republic'],
  ['dz', 'Algeria'],
  ['ec', 'Ecuador'],
  ['ee', 'Estonia'],
  ['eg', 'Egypt'],
  ['er', 'Eritrea'],
  ['es', 'Spain', ['espana', 'españa']],
  ['et', 'Ethiopia'],
  ['fi', 'Finland'],
  ['fj', 'Fiji'],
  ['fm', 'Micronesia'],
  ['fr', 'France'],
  ['ga', 'Gabon'],
  ['gb', 'United Kingdom', ['uk', 'britain', 'great britain', 'england']],
  ['gd', 'Grenada'],
  ['ge', 'Georgia'],
  ['gh', 'Ghana'],
  ['gm', 'Gambia'],
  ['gn', 'Guinea'],
  ['gq', 'Equatorial Guinea'],
  ['gr', 'Greece'],
  ['gt', 'Guatemala'],
  ['gw', 'Guinea-Bissau'],
  ['gy', 'Guyana'],
  ['hn', 'Honduras'],
  ['hr', 'Croatia'],
  ['ht', 'Haiti'],
  ['hu', 'Hungary'],
  ['id', 'Indonesia'],
  ['ie', 'Ireland'],
  ['il', 'Israel'],
  ['in', 'India'],
  ['iq', 'Iraq'],
  ['ir', 'Iran'],
  ['is', 'Iceland'],
  ['it', 'Italy'],
  ['jm', 'Jamaica'],
  ['jo', 'Jordan'],
  ['jp', 'Japan'],
  ['ke', 'Kenya'],
  ['kg', 'Kyrgyzstan'],
  ['kh', 'Cambodia'],
  ['ki', 'Kiribati'],
  ['km', 'Comoros'],
  ['kp', 'North Korea'],
  ['kr', 'South Korea', ['korea', 'republic of korea']],
  ['kw', 'Kuwait'],
  ['kz', 'Kazakhstan'],
  ['la', 'Laos'],
  ['lb', 'Lebanon'],
  ['lc', 'Saint Lucia', ['st lucia']],
  ['li', 'Liechtenstein'],
  ['lk', 'Sri Lanka'],
  ['lr', 'Liberia'],
  ['ls', 'Lesotho'],
  ['lt', 'Lithuania'],
  ['lu', 'Luxembourg'],
  ['lv', 'Latvia'],
  ['ly', 'Libya'],
  ['ma', 'Morocco'],
  ['mc', 'Monaco'],
  ['md', 'Moldova'],
  ['me', 'Montenegro'],
  ['mg', 'Madagascar'],
  ['mk', 'North Macedonia', ['macedonia']],
  ['ml', 'Mali'],
  ['mm', 'Myanmar', ['burma']],
  ['mn', 'Mongolia'],
  ['mr', 'Mauritania'],
  ['mt', 'Malta'],
  ['mu', 'Mauritius'],
  ['mv', 'Maldives'],
  ['mw', 'Malawi'],
  ['mx', 'Mexico'],
  ['my', 'Malaysia'],
  ['mz', 'Mozambique'],
  ['na', 'Namibia'],
  ['ne', 'Niger'],
  ['ng', 'Nigeria'],
  ['ni', 'Nicaragua'],
  ['nl', 'Netherlands', ['holland']],
  ['no', 'Norway'],
  ['np', 'Nepal'],
  ['nz', 'New Zealand'],
  ['om', 'Oman'],
  ['pa', 'Panama'],
  ['pe', 'Peru'],
  ['pg', 'Papua New Guinea'],
  ['ph', 'Philippines'],
  ['pk', 'Pakistan'],
  ['pl', 'Poland'],
  ['pt', 'Portugal'],
  ['py', 'Paraguay'],
  ['qa', 'Qatar'],
  ['ro', 'Romania'],
  ['rs', 'Serbia'],
  ['ru', 'Russia', ['russian federation']],
  ['rw', 'Rwanda'],
  ['sa', 'Saudi Arabia'],
  ['sb', 'Solomon Islands'],
  ['sc', 'Seychelles'],
  ['sd', 'Sudan'],
  ['se', 'Sweden'],
  ['sg', 'Singapore'],
  ['si', 'Slovenia'],
  ['sk', 'Slovakia'],
  ['sl', 'Sierra Leone'],
  ['sm', 'San Marino'],
  ['sn', 'Senegal'],
  ['so', 'Somalia'],
  ['sr', 'Suriname'],
  ['ss', 'South Sudan'],
  ['sv', 'El Salvador'],
  ['sy', 'Syria'],
  ['sz', 'Eswatini', ['swaziland']],
  ['td', 'Chad'],
  ['tg', 'Togo'],
  ['th', 'Thailand'],
  ['tj', 'Tajikistan'],
  ['tl', 'Timor-Leste', ['east timor']],
  ['tm', 'Turkmenistan'],
  ['tn', 'Tunisia'],
  ['to', 'Tonga'],
  ['tr', 'Turkey', ['turkiye', 'türkiye']],
  ['tt', 'Trinidad and Tobago', ['trinidad']],
  ['tw', 'Taiwan'],
  ['tz', 'Tanzania'],
  ['ua', 'Ukraine'],
  ['ug', 'Uganda'],
  ['us', 'United States', ['usa', 'us', 'america', 'united states of america']],
  ['uy', 'Uruguay'],
  ['uz', 'Uzbekistan'],
  ['va', 'Vatican City', ['vatican']],
  ['ve', 'Venezuela'],
  ['vn', 'Vietnam'],
  ['vu', 'Vanuatu'],
  ['ws', 'Samoa'],
  ['ye', 'Yemen'],
  ['za', 'South Africa'],
  ['zm', 'Zambia'],
  ['zw', 'Zimbabwe'],
].map(([code, name, aliases = []]) => ({ code, name, aliases }));

// Strips accents, punctuation and a leading "the" so "Côte d'Ivoire",
// "cote divoire" and "The Gambia" all compare equal to their entry.
function normalise(input) {
  return String(input ?? '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/^the\s+/, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// The flag emoji is the two ISO letters as regional indicators — derived, so
// there's no second table to keep in sync with the country list.
function flagEmoji(code) {
  return [...code.toUpperCase()].map((letter) => String.fromCodePoint(0x1f1e6 + letter.charCodeAt(0) - 65)).join('');
}

function flagImageUrl(code) {
  return `https://flagcdn.com/w320/${code}.png`;
}

function randomCountry() {
  return COUNTRIES[Math.floor(Math.random() * COUNTRIES.length)];
}

function isCorrectAnswer(country, guess) {
  const answer = normalise(guess);
  if (!answer) return false;
  return answer === normalise(country.name) || country.aliases.some((alias) => normalise(alias) === answer);
}

module.exports = { COUNTRIES, randomCountry, isCorrectAnswer, flagEmoji, flagImageUrl, normalise };
